--
-- Table structure for table `checklist`
--

DROP TABLE IF EXISTS checklist CASCADE;
CREATE TABLE checklist (
  ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(35) NOT NULL DEFAULT '',
  date date  not null,
  description varchar(75) NULL DEFAULT ''
) ;



DROP TABLE IF EXISTS checkitem;
CREATE TABLE checkitem (
  ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  checklist_ID int NOT NULL DEFAULT '0',
  description char(75) NULL DEFAULT '',
  CONSTRAINT checkitem_clfk_1 FOREIGN KEY (checklist_ID) REFERENCES checklist (ID)
) ;

GRANT ALL ON checklist TO PUBLIC;