spring:
    sql:
        init:
            mode: ALWAYS
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        open-in-view: false
        hibernate:
            ddl-auto: create